### ISSUE TITLE
TypeError: make() got an unexpected keyword argument 'physical_noise_std_ratio'

### ISSUE THREAD

**Issue by GoingMyWay** [galdl/rl_delay_basic#2]
Hi, it seems that `physical_noise_std_ratio` in `orig_env = gym.make(config.env_name, physical_noise_std_ratio=config.physical_noise_std_ratio)`  is not found. Will you share which version of gym should I use?

**Comment by galdl** [comment]
Thanks for raising this. The added noise to the cartpole and acrobot envs currently requires to manually update the gym library with the modified constructors. I'll commit the modified python files and include instructions on how to update the gym library.

**Comment by GoingMyWay** [comment]
Thank you for your help, I am looking forward to running the code.

**Comment by galdl** [comment]
Please have a look at the newly added installation instructions and code updates. You should be able to run now and choose whether to use the noisy environments.
